# Generated by Django 4.1.5 on 2023-02-24 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caterogy',
            new_name='Category',
        ),
    ]
