# Generated by Django 4.1.5 on 2023-03-10 23:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=255)),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Not Started'), (2, 'In Progress'), (3, 'Complete')], default=0)),
                ('date_created', models.DateField(default=datetime.datetime(2023, 3, 10, 23, 29, 27, 383631, tzinfo=datetime.timezone.utc))),
                ('date_due', models.DateField(blank=True, default=None, null=True)),
                ('date_completed', models.DateField(blank=True, default=None, null=True)),
                ('repeat', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('isSeen', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('interval', models.CharField(blank=True, choices=[('Daily', 'Every Day'), ('Weekly', 'Every Week'), ('Monthly', 'Every Month'), ('Annual', 'Every Year')], max_length=10, null=True)),
                ('intervalLength', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='taskManager.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('alt_txt', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 3, 10, 23, 29, 27, 383966, tzinfo=datetime.timezone.utc))),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='taskManager.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Caterogy',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dep_name',
            new_name='name',
        ),
    ]
