# Generated by Django 4.1.5 on 2023-02-24 22:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0002_rename_caterogy_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('task_name', models.CharField(max_length=150)),
                ('task_desc', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('date_created', models.DateField(default=datetime.date(2023, 2, 24))),
                ('date_due', models.DateField()),
                ('date_completed', models.DateField()),
                ('repeat', models.BooleanField(default=False)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='taskManager.category')),
            ],
        ),
    ]
