# Generated by Django 4.1.5 on 2023-03-10 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0002_category_task_upload_delete_caterogy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 3, 10, 23, 32, 45, 950905, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='upload',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 23, 32, 45, 951252, tzinfo=datetime.timezone.utc)),
        ),
    ]
