# Generated by Django 4.1.5 on 2023-03-11 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0003_alter_task_date_created_alter_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 3, 11, 9, 7, 46, 487332, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='interval',
            field=models.CharField(blank=True, choices=[('', 'Interval'), ('Daily', 'Day(s)'), ('Weekly', 'Week(s)'), ('Monthly', 'Month(s)'), ('Annual', 'Year(s)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 9, 7, 46, 487721, tzinfo=datetime.timezone.utc)),
        ),
    ]
