# Generated by Django 4.1.5 on 2023-02-24 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0006_alter_task_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dep_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 2, 24, 22, 57, 53, 22701, tzinfo=datetime.timezone.utc)),
        ),
    ]
