# Generated by Django 4.1.5 on 2023-02-24 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0008_alter_task_date_created_alter_task_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='cat_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='uid',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='date_completed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 2, 24, 23, 1, 4, 285950, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_due',
            field=models.DateField(null=True),
        ),
    ]
