# Generated by Django 4.1.5 on 2023-03-24 23:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taskManager.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskManager', '0011_alter_task_date_created_alter_upload_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 3, 24, 23, 24, 52, 775748, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, default=taskManager.models.get_admin_user, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upload',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 23, 24, 52, 776168, tzinfo=datetime.timezone.utc)),
        ),
    ]
