# Generated by Django 4.1.5 on 2023-02-24 23:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0011_alter_task_date_created_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 2, 24, 23, 21, 29, 220527, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Repeating_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('Day', 'Daily'), ('Week', 'Weekly'), ('BiWeek', 'Biweekly'), ('Month', 'Monthly'), ('Quart', 'Quarterly'), ('BiAnn', 'Semiannualy'), ('Ann', 'Annualy')], max_length=10)),
                ('length', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='taskManager.task')),
            ],
        ),
    ]
