# Generated by Django 4.1.5 on 2023-02-24 23:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskManager', '0013_alter_task_date_created_uploads_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('alt_txt', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 2, 24, 23, 30, 25, 237920, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 23, 30, 25, 237663, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 2, 24, 23, 30, 25, 237196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Uploads',
        ),
        migrations.AddField(
            model_name='upload',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='taskManager.task'),
        ),
        migrations.AddField(
            model_name='upload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
